version: 0.2

env:
  variables:
    AWS_REGION_2: "us-east-1"
    REACT_APP_API_SERVICE_URL: "http://localhost:5004"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging in to ecr...
      - >
        aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - docker login -u saikiranreddykonda -p Bostoncity@001
      - echo building dev images...
      - docker-compose up -d --build
      - echo building prod images...
      - >
        docker build \
          -f be/Dockerfile \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-be:dev \
          ./be
      - >
        docker build \
          -f fe/Dockerfile \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-fe:dev \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_API_SERVICE_URL=$REACT_APP_API_SERVICE_URL \
          ./fe
  post_build:
    commands:
    - echo pushing prod images to ecr...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-be:dev
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-fe:dev
